<?php

/**
 * @file
 * Exclude Node Title module install/schema hooks.
 */

// Dynamically generated variable data was detected on the following lines.
// /exclude_node_title/exclude_node_title.admin.inc line 69.
// /exclude_node_title/exclude_node_title.admin.inc line 97.
// /exclude_node_title/exclude_node_title.module line 278.
// /exclude_node_title/exclude_node_title.module line 204.
// /exclude_node_title/exclude_node_title.module line 279.
// /exclude_node_title/exclude_node_title.module line 366.

/**
 * Implements hook_uninstall().
 */
function exclude_node_title_uninstall() {
  config_clear('exclude_node_title.settings', 'exclude_node_title_nid_list');
  config_clear('exclude_node_title.settings', 'exclude_node_title_search');
  config_clear('exclude_node_title.settings', 'exclude_node_title_hide_using_css');
  config_clear('exclude_node_title.settings', 'exclude_node_title_themes_supporting_css');
  foreach (_node_types_build()->names as $key => $val) {
    config_clear('exclude_node_title.settings', 'exclude_node_title_content_type_value_' . $key);
    config_clear('exclude_node_title.settings', 'exclude_node_title_content_type_modes_' . $key);
  }
}

// TODO The old hook_update_N functions cannot be applied to Backdrop.
function exclude_node_title_update_7100() { }

/**
 * Implements hook_update_last_removed().
 */
function exclude_node_title_update_last_removed() {
  return 7100;
}

/**
 * Migrate exclude_node_title variables to config.
 */
function exclude_node_title_update_1000() {
  $config = config('exclude_node_title.settings');
  $config->set('exclude_node_title_search', update_variable_get('exclude_node_title_search', '0'));
  $config->set('exclude_node_title_translation_sync', update_variable_get('exclude_node_title_translation_sync', TRUE));
  $config->set('exclude_node_title_hide_using_css', update_variable_get('exclude_node_title_hide_using_css', '0'));
  $config->set('exclude_node_title_themes_supporting_css', update_variable_get('exclude_node_title_themes_supporting_css', array()));
  $config->set('exclude_node_title_content_type_value_node_type', update_variable_get('exclude_node_title_content_type_value_node_type', 'dynamic variable in file /exclude_node_title/exclude_node_title.admin.inc line 69'));
  $config->set('exclude_node_title_content_type_modes_node_type', update_variable_get('exclude_node_title_content_type_modes_node_type', 'dynamic variable in file /exclude_node_title/exclude_node_title.admin.inc line 97'));
  $config->set('exclude_node_title_remove_title', update_variable_get('exclude_node_title_remove_title', array()));
  $config->set('exclude_node_title_content_type_value_key', update_variable_get('exclude_node_title_content_type_value_key', 'dynamic variable in file /exclude_node_title/exclude_node_title.module line 278'));
  $config->set('exclude_node_title_content_type_value_formnodetype', update_variable_get('exclude_node_title_content_type_value_formnodetype', 'dynamic variable in file /exclude_node_title/exclude_node_title.module line 204'));
  $config->set('exclude_node_title_nid_list', update_variable_get('exclude_node_title_nid_list', array()));
  $config->set('exclude_node_title_content_type_modes_key', update_variable_get('exclude_node_title_content_type_modes_key', 'dynamic variable in file /exclude_node_title/exclude_node_title.module line 279'));
  $config->set('exclude_node_title_content_type_value_typetype', update_variable_get('exclude_node_title_content_type_value_typetype', 'dynamic variable in file /exclude_node_title/exclude_node_title.module line 366'));
  $config->save();

  update_variable_del('exclude_node_title_search');
  update_variable_del('exclude_node_title_translation_sync');
  update_variable_del('exclude_node_title_hide_using_css');
  update_variable_del('exclude_node_title_themes_supporting_css');
  update_variable_del('exclude_node_title_content_type_value_node_type');
  update_variable_del('exclude_node_title_content_type_modes_node_type');
  update_variable_del('exclude_node_title_remove_title');
  update_variable_del('exclude_node_title_content_type_value_key');
  update_variable_del('exclude_node_title_content_type_value_formnodetype');
  update_variable_del('exclude_node_title_nid_list');
  update_variable_del('exclude_node_title_content_type_modes_key');
  update_variable_del('exclude_node_title_content_type_value_typetype');
}
